# exmaple netlify.toml
# Of course i can move all the items in a 'dist' folder

[build]
# command = 'yarn run build'
# functions = "functions"
# . means deploying root folder, i will no longer be asked where my published path is.,

publish = "dist"

#Markup Language
https://www.netlify.com/img/deploy/button.svg?repository=https://github.com/AmirDevops/Netlify-1

